fix syntax

diff --git a/.github/workflows/openwrt.yml b/.github/workflows/openwrt.yml
--- a/.github/workflows/openwrt.yml
+++ b/.github/workflows/openwrt.yml
@@ -60,7 +60,7 @@ jobs:
 
       - name: Build rust
         run: |
-	  make package/rust/compile V=s || echo "xxxxx Failed: rust xxxxx"
+          make package/rust/compile V=s || echo "xxxxx Failed: rust xxxxx"
 
       - name: Prepare solution
         run: |
