build rust

diff --git a/.github/workflows/openwrt.yml b/.github/workflows/openwrt.yml
--- a/.github/workflows/openwrt.yml
+++ b/.github/workflows/openwrt.yml
@@ -58,6 +58,10 @@ jobs:
             done
           done
 
+      - name: Build rust
+        run: |
+	  make package/rust/compile V=s || echo "xxxxx Failed: rust xxxxx"
+
       - name: Prepare solution
         run: |
           mkdir -p ipks_feed
